"""Generates the pack glyph data for the app and the admin, and the SVG brand files.

Usage: python3 scripts/brand/pack-glyphs/generate.py
Edit shapes in glyphs.py (120-unit box, y down, evenodd knockouts); review them with workbench.py.
"""
import json, math, os, re, sys
HERE = os.path.dirname(os.path.abspath(__file__))
__file__ = os.path.join(HERE, 'workbench.py')
exec(open(__file__).read().split("if __name__")[0])

FAMILIES = {
    'beasts': ['wolf', 'falcon', 'horse', 'oryx', 'camel', 'ibex', 'leopard', 'lion', 'rhino', 'bull', 'shark', 'scorpion'],
    'myths': ['spartan', 'shield', 'pegasus', 'phoenix', 'minotaur', 'trident', 'laurel', 'torch'],
    'marks': ['bolt', 'peak', 'waves', 'flame', 'tally', 'chevrons', 'spark'],
}
# Heads rise out of the bottom of the patch like a crest; everything else floats centred.
RISE = {'falcon', 'horse', 'oryx', 'lion', 'rhino', 'ibex', 'leopard', 'bull', 'pegasus'}
# Optical corrections (scale multiplier, dx, dy in patch units).
TUNE = {'shield': (0.94, 0, 0), 'laurel': (1.06, 0, 0), 'spark': (0.92, 0, 0), 'chevrons': (0.96, 0, 2), 'wolf': (1.04, 0, 0),
        'scorpion': (1.08, 0, 0), 'shark': (1.06, 0, 0), 'camel': (1.06, 0, 1), 'trident': (1.02, 0, 0), 'torch': (1.0, 0, 0)}

WS = 88 / 148.74
def num(v):
    t = f'{v:.1f}'
    return t[:-2] if t.endswith('.0') else t


def wolf_d():
    parts = []
    for d in WOLF_PATHS:
        toks = re.findall(r'[MLCZ]|-?\d+\.?\d*', d)
        cmd, nums, open_sub = None, [], False
        for t in toks:
            if t in 'MLCZ':
                if t == 'M' and open_sub:
                    parts.append('Z')
                if t == 'Z':
                    parts.append('Z')
                    open_sub = False
                else:
                    parts.append(t)
                    open_sub = True
                continue
            nums.append(float(t))
            if len(nums) == 2:
                parts.append(f'{num(16 + nums[0] * WS)} {num(19.5 + nums[1] * WS)}')
                nums = []
        if open_sub:
            parts.append('Z')
    out = ''
    for p in parts:
        if p in 'MLCZ':
            out += p
        else:
            out += (' ' if out and out[-1] not in 'MLCZ' else '') + p
    return out


def pts_of(name):
    if name == 'wolf':
        return [(16, 19.5), (16 + 148.74 * WS, 19.5 + 136.86 * WS)]
    return [p for sub in G[name] for p in sub]

def d_of(name):
    if name == 'wolf':
        return wolf_d()
    return ''.join('M' + 'L'.join(f'{num(x)} {num(y)}' for x, y in sub) + 'Z' for sub in G[name])

out = {}
for fam, ids in FAMILIES.items():
    for n in ids:
        P = pts_of(n)
        xs, ys = [p[0] for p in P], [p[1] for p in P]
        x0, y0, x1, y1 = min(xs), min(ys), max(xs), max(ys)
        w, h = x1 - x0, y1 - y0
        k, dx, dy = TUNE.get(n, (1, 0, 0))
        if n in RISE:
            s = 76 / h * k
            tx, ty = 50 - (x0 + w / 2) * s, 102 - y1 * s
        else:
            s = 64 / max(w, h) * k
            tx, ty = 50 - (x0 + w / 2) * s, 50 - (y0 + h / 2) * s
        out[n] = {'d': d_of(n), 't': [round(tx + dx, 2), round(ty + dy, 2), round(s, 4)]}

def ts(header):
    lines = [header,
             "export type GlyphFamily = 'beasts' | 'myths' | 'marks';",
             "export interface Glyph {",
             "  /** Outline in a 120-unit box; knockouts rely on fillRule=\"evenodd\". */",
             "  d: string;",
             "  /** translate x, translate y, scale — places the glyph in a 100-unit round patch. */",
             "  t: [number, number, number];",
             "}",
             '',
             'export const GLYPH_FAMILIES: Record<GlyphFamily, string[]> = ' + json.dumps(FAMILIES) + ';',
             '',
             'export const GLYPHS: Record<string, Glyph> = {']
    for n, g in out.items():
        lines.append(f"  {n}: {{ t: {json.dumps(g['t'])}, d: '{g['d']}' }},")
    lines.append('};')
    lines.append('')
    return '\n'.join(lines)

HEADER = """// Generated by scripts/brand/pack-glyphs/generate.py — do not edit by hand.
// Beast Tribe's own pack glyphs, drawn in the Operation Beast wolf's geometry (the italic
// cut, flat feet, triangle eye): Beasts of Arabia, Greek myths, and brand marks.
"""
root = os.path.abspath(os.path.join(HERE, '..', '..', '..')) + '/'
open(root + 'src/components/brand/glyphs.ts', 'w').write(ts(HEADER))
open(root + 'admin/src/components/brand/glyphs.ts', 'w').write(ts(HEADER))
print(sum(len(g['d']) for g in out.values()), 'chars;', out['wolf']['d'][:120])

import os
gdir = root + 'assets/brand/pack-glyphs/'
os.makedirs(gdir, exist_ok=True)
for fam, ids in FAMILIES.items():
    for n in ids:
        open(gdir + f'{n}.svg', 'w').write(f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 120 120"><title>{n}</title><path fill="currentColor" fill-rule="evenodd" d="{out[n]["d"]}"/></svg>\n')
print('exported', sum(len(v) for v in FAMILIES.values()), 'glyph svgs')
